name: Notify Discussions

on:
  push:
  # schedule:
  #   - cron: '30 00 * * 1-5' # 平日09:30 (JST)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  notify:
    env:
      MESSAGE_PREFIX: "【${{ github.event.repository.name }}】"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo "${{ env.MESSAGE_PREFIX }}"
