on:
  workflow_dispatch:
  schedule:
    - cron: '25 * * * 1-5' # 平日毎時39分 (JST)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: event_name
        run: echo ${{ github.event_name }}
